Update mold-update-dbpassword.in

diff --git a/setup/bindir/mold-update-dbpassword.in b/setup/bindir/mold-update-dbpassword.in
--- a/setup/bindir/mold-update-dbpassword.in
+++ b/setup/bindir/mold-update-dbpassword.in
@@ -206,7 +206,7 @@ if [ -n "$key" ]; then
   else
     sed -i "s/$curDbCloudEncPassword/$newDbCloudEncPassword/g" $DB_FILE
     sed -i "s/$curDbUsageEncPassword/$newDbUsageEncPassword/g" $DB_FILE
-    openssl enc -aes-256-cbc -K $hex_key -pass pass:$kek_pass -saltlen 16 -md sha256 -iter 100000 -in db.properties -out db.properties.enc 
+    openssl enc -aes-256-cbc -K $hex_key -pass pass:$kek_pass -saltlen 16 -md sha256 -iter 100000 -in db.properties -out db.properties.enc
     res=$?
     if [ $res -eq 0 ];then
       rm -rf $DB_FILE
@@ -226,10 +226,10 @@ mysql -uroot -p$curdbpass -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$newp
 
 res=$?
 if [ $res -eq 0 ];then
-   echo " ### Mysql root, cloud password change completed ### " 
+  echo " ### Mysql root, cloud password change completed ### " 
 else
-   echo " ### Mysql root, cloud password change failed ### "
-   exit 1
+  echo " ### Mysql root, cloud password change failed ### "
+  exit 1
 fi
 
 
@@ -250,6 +250,7 @@ do
   newpass=01010101
   curdbpass=01010101
   newpass_check=01010101
+  hex_key=01010101
 done
 
 
